# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-snowflake-database
  description: "All data in Snowflake is stored in database tables, logically structured as collections of columns and rows"
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component







